# Generated by Django 2.1.7 on 2019-03-12 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskman', '0004_auto_20190312_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='members',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
