# Generated by Django 2.1.7 on 2019-03-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskman', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='creator',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
